#SIT Server Configuration
server:
 port: 8091
 
 #Database Configuration
spring:
  datasource:
    driver-class-name:  oracle.jdbc.OracleDriver
    url:  jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: tiger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
